/**
 * Model Catalog
 * This is MINT Model Catalog You can find out more about     Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)
 *
 * OpenAPI spec version: 0.0.2
 * Contact: mosorio@isi.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Parameter from './Parameter';

/**
 * The CAG model module.
 * @module model/CAG
 * @version 0.0.2
 */
class CAG {
    /**
     * Constructs a new <code>CAG</code>.
     * @alias module:model/CAG
     * @param id {String} 
     */
    constructor(id) { 
        
        CAG.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>CAG</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CAG} obj Optional instance to populate.
     * @return {module:model/CAG} The populated <code>CAG</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CAG();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], ['String']);
            }
            if (data.hasOwnProperty('hasPart')) {
                obj['hasPart'] = ApiClient.convertToType(data['hasPart'], [Parameter]);
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
CAG.prototype['id'] = undefined;

/**
 * @member {Array.<String>} type
 */
CAG.prototype['type'] = undefined;

/**
 * Array of Parameter or Variables
 * @member {Array.<module:model/Parameter>} hasPart
 */
CAG.prototype['hasPart'] = undefined;

/**
 * @member {String} label
 */
CAG.prototype['label'] = undefined;






export default CAG;

