/**
 * Model Catalog
 * This is MINT Model Catalog You can find out more about     Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)
 *
 * OpenAPI spec version: 0.0.2
 * Contact: mosorio@isi.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VariablePresentation from './VariablePresentation';

/**
 * The DatasetSpecification model module.
 * @module model/DatasetSpecification
 * @version 0.0.2
 */
class DatasetSpecification {
    /**
     * Constructs a new <code>DatasetSpecification</code>.
     * @alias module:model/DatasetSpecification
     * @param id {String} 
     */
    constructor(id) { 
        
        DatasetSpecification.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>DatasetSpecification</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DatasetSpecification} obj Optional instance to populate.
     * @return {module:model/DatasetSpecification} The populated <code>DatasetSpecification</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DatasetSpecification();

            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('hasFormat')) {
                obj['hasFormat'] = ApiClient.convertToType(data['hasFormat'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('hasDimensionality')) {
                obj['hasDimensionality'] = ApiClient.convertToType(data['hasDimensionality'], 'Number');
            }
            if (data.hasOwnProperty('hasPresentation')) {
                obj['hasPresentation'] = ApiClient.convertToType(data['hasPresentation'], [VariablePresentation]);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], ['String']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} label
 */
DatasetSpecification.prototype['label'] = undefined;

/**
 * @member {String} hasFormat
 */
DatasetSpecification.prototype['hasFormat'] = undefined;

/**
 * @member {String} description
 */
DatasetSpecification.prototype['description'] = undefined;

/**
 * @member {Number} hasDimensionality
 */
DatasetSpecification.prototype['hasDimensionality'] = undefined;

/**
 * @member {Array.<module:model/VariablePresentation>} hasPresentation
 */
DatasetSpecification.prototype['hasPresentation'] = undefined;

/**
 * @member {Array.<String>} type
 */
DatasetSpecification.prototype['type'] = undefined;

/**
 * @member {String} id
 */
DatasetSpecification.prototype['id'] = undefined;






export default DatasetSpecification;

