/**
 * Model Catalog
 * This is MINT Model Catalog You can find out more about     Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)
 *
 * OpenAPI spec version: 0.0.2
 * Contact: mosorio@isi.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Model model module.
 * @module model/Model
 * @version 0.0.2
 */
class Model {
    /**
     * Constructs a new <code>Model</code>.
     * @alias module:model/Model
     * @param id {String} 
     */
    constructor(id) { 
        
        Model.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>Model</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Model} obj Optional instance to populate.
     * @return {module:model/Model} The populated <code>Model</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Model();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], ['String']);
            }
            if (data.hasOwnProperty('hasSoftwareVersion')) {
                obj['hasSoftwareVersion'] = ApiClient.convertToType(data['hasSoftwareVersion'], [Object]);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('hasModelCategory')) {
                obj['hasModelCategory'] = ApiClient.convertToType(data['hasModelCategory'], ['String']);
            }
            if (data.hasOwnProperty('hasDocumentation')) {
                obj['hasDocumentation'] = ApiClient.convertToType(data['hasDocumentation'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Model.prototype['id'] = undefined;

/**
 * @member {String} label
 */
Model.prototype['label'] = undefined;

/**
 * @member {Array.<String>} type
 */
Model.prototype['type'] = undefined;

/**
 * @member {Array.<Object>} hasSoftwareVersion
 */
Model.prototype['hasSoftwareVersion'] = undefined;

/**
 * @member {String} description
 */
Model.prototype['description'] = undefined;

/**
 * @member {Array.<String>} hasModelCategory
 */
Model.prototype['hasModelCategory'] = undefined;

/**
 * @member {Array.<String>} hasDocumentation
 */
Model.prototype['hasDocumentation'] = undefined;






export default Model;

