/**
 * Model Catalog
 * This is MINT Model Catalog You can find out more about     Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)
 *
 * OpenAPI spec version: 0.0.2
 * Contact: mosorio@isi.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Parameter model module.
 * @module model/Parameter
 * @version 0.0.2
 */
class Parameter {
    /**
     * Constructs a new <code>Parameter</code>.
     * @alias module:model/Parameter
     * @param id {String} 
     */
    constructor(id) { 
        
        Parameter.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>Parameter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Parameter} obj Optional instance to populate.
     * @return {module:model/Parameter} The populated <code>Parameter</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Parameter();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], ['String']);
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('hasDefaultValue')) {
                obj['hasDefaultValue'] = ApiClient.convertToType(data['hasDefaultValue'], 'String');
            }
            if (data.hasOwnProperty('hasDataType')) {
                obj['hasDataType'] = ApiClient.convertToType(data['hasDataType'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Parameter.prototype['id'] = undefined;

/**
 * @member {Array.<String>} type
 */
Parameter.prototype['type'] = undefined;

/**
 * @member {String} label
 */
Parameter.prototype['label'] = undefined;

/**
 * @member {String} description
 */
Parameter.prototype['description'] = undefined;

/**
 * @member {String} hasDefaultValue
 */
Parameter.prototype['hasDefaultValue'] = undefined;

/**
 * @member {String} hasDataType
 */
Parameter.prototype['hasDataType'] = undefined;






export default Parameter;

