/**
 * Model Catalog
 * This is MINT Model Catalog You can find out more about     Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)
 *
 * OpenAPI spec version: 0.0.2
 * Contact: mosorio@isi.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Process model module.
 * @module model/Process
 * @version 0.0.2
 */
class Process {
    /**
     * Constructs a new <code>Process</code>.
     * @alias module:model/Process
     * @param id {String} 
     */
    constructor(id) { 
        
        Process.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>Process</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Process} obj Optional instance to populate.
     * @return {module:model/Process} The populated <code>Process</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Process();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], ['String']);
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('influences')) {
                obj['influences'] = ApiClient.convertToType(data['influences'], [Process]);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Process.prototype['id'] = undefined;

/**
 * @member {Array.<String>} type
 */
Process.prototype['type'] = undefined;

/**
 * @member {String} label
 */
Process.prototype['label'] = undefined;

/**
 * Property that describe the causal relationship between two processes, two variables, a process and a variable or a variable and a process
 * @member {Array.<module:model/Process>} influences
 */
Process.prototype['influences'] = undefined;

/**
 * @member {String} description
 */
Process.prototype['description'] = undefined;






export default Process;

