/**
 * Model Catalog
 * This is MINT Model Catalog You can find out more about     Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)
 *
 * OpenAPI spec version: 0.0.2
 * Contact: mosorio@isi.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Unit from './Unit';

/**
 * The TimeInterval model module.
 * @module model/TimeInterval
 * @version 0.0.2
 */
class TimeInterval {
    /**
     * Constructs a new <code>TimeInterval</code>.
     * @alias module:model/TimeInterval
     * @param id {String} 
     */
    constructor(id) { 
        
        TimeInterval.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>TimeInterval</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TimeInterval} obj Optional instance to populate.
     * @return {module:model/TimeInterval} The populated <code>TimeInterval</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TimeInterval();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], ['String']);
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('usesUnit')) {
                obj['usesUnit'] = Unit.constructFromObject(data['usesUnit']);
            }
            if (data.hasOwnProperty('hasValue')) {
                obj['hasValue'] = ApiClient.convertToType(data['hasValue'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
TimeInterval.prototype['id'] = undefined;

/**
 * @member {Array.<String>} type
 */
TimeInterval.prototype['type'] = undefined;

/**
 * @member {String} label
 */
TimeInterval.prototype['label'] = undefined;

/**
 * @member {String} description
 */
TimeInterval.prototype['description'] = undefined;

/**
 * @member {module:model/Unit} usesUnit
 */
TimeInterval.prototype['usesUnit'] = undefined;

/**
 * @member {Number} hasValue
 */
TimeInterval.prototype['hasValue'] = undefined;






export default TimeInterval;

