/**
 * Model Catalog
 * This is MINT Model Catalog You can find out more about     Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)
 *
 * OpenAPI spec version: 0.0.2
 * Contact: mosorio@isi.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DatasetSpecification from './DatasetSpecification';
import Unit from './Unit';

/**
 * The VariablePresentation model module.
 * @module model/VariablePresentation
 * @version 0.0.2
 */
class VariablePresentation {
    /**
     * Constructs a new <code>VariablePresentation</code>.
     * @alias module:model/VariablePresentation
     * @param id {String} 
     */
    constructor(id) { 
        
        VariablePresentation.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>VariablePresentation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VariablePresentation} obj Optional instance to populate.
     * @return {module:model/VariablePresentation} The populated <code>VariablePresentation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VariablePresentation();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], ['String']);
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('hasLongName')) {
                obj['hasLongName'] = ApiClient.convertToType(data['hasLongName'], 'String');
            }
            if (data.hasOwnProperty('hasShortName')) {
                obj['hasShortName'] = ApiClient.convertToType(data['hasShortName'], 'String');
            }
            if (data.hasOwnProperty('hasStandardVariable')) {
                obj['hasStandardVariable'] = ApiClient.convertToType(data['hasStandardVariable'], [DatasetSpecification]);
            }
            if (data.hasOwnProperty('hasRelevanceLevel')) {
                obj['hasRelevanceLevel'] = ApiClient.convertToType(data['hasRelevanceLevel'], 'Number');
            }
            if (data.hasOwnProperty('usesUnit')) {
                obj['usesUnit'] = Unit.constructFromObject(data['usesUnit']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
VariablePresentation.prototype['id'] = undefined;

/**
 * @member {Array.<String>} type
 */
VariablePresentation.prototype['type'] = undefined;

/**
 * @member {String} label
 */
VariablePresentation.prototype['label'] = undefined;

/**
 * @member {String} description
 */
VariablePresentation.prototype['description'] = undefined;

/**
 * @member {String} hasLongName
 */
VariablePresentation.prototype['hasLongName'] = undefined;

/**
 * @member {String} hasShortName
 */
VariablePresentation.prototype['hasShortName'] = undefined;

/**
 * @member {Array.<module:model/DatasetSpecification>} hasStandardVariable
 */
VariablePresentation.prototype['hasStandardVariable'] = undefined;

/**
 * @member {Number} hasRelevanceLevel
 */
VariablePresentation.prototype['hasRelevanceLevel'] = undefined;

/**
 * @member {module:model/Unit} usesUnit
 */
VariablePresentation.prototype['usesUnit'] = undefined;






export default VariablePresentation;

