/**
 * Model Catalog
 * This is MINT Model Catalog You can find out more about     Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)
 *
 * OpenAPI spec version: 0.0.2
 * Contact: mosorio@isi.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ApiResponse from './model/ApiResponse';
import CAG from './model/CAG';
import DatasetSpecification from './model/DatasetSpecification';
import Model from './model/Model';
import ModelConfiguration from './model/ModelConfiguration';
import ModelVersion from './model/ModelVersion';
import Parameter from './model/Parameter';
import Process from './model/Process';
import TimeInterval from './model/TimeInterval';
import Unit from './model/Unit';
import User from './model/User';
import VariablePresentation from './model/VariablePresentation';
import DatasetspecificationApi from './api/DatasetspecificationApi';
import ModelApi from './api/ModelApi';
import ModelconfigurationApi from './api/ModelconfigurationApi';
import ModelversionApi from './api/ModelversionApi';
import ParameterApi from './api/ParameterApi';
import UserApi from './api/UserApi';


/**
* This_is_MINT_Model_Catalog_You_can_find_out_more_about_____Model_Catalog_at__https__w3id_org_mint_modelCatalog__https__w3id_org_mint_modelCatalog_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MintApi = require('index'); // See note below*.
* var xxxSvc = new MintApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MintApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MintApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MintApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.2
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ApiResponse model constructor.
     * @property {module:model/ApiResponse}
     */
    ApiResponse,

    /**
     * The CAG model constructor.
     * @property {module:model/CAG}
     */
    CAG,

    /**
     * The DatasetSpecification model constructor.
     * @property {module:model/DatasetSpecification}
     */
    DatasetSpecification,

    /**
     * The Model model constructor.
     * @property {module:model/Model}
     */
    Model,

    /**
     * The ModelConfiguration model constructor.
     * @property {module:model/ModelConfiguration}
     */
    ModelConfiguration,

    /**
     * The ModelVersion model constructor.
     * @property {module:model/ModelVersion}
     */
    ModelVersion,

    /**
     * The Parameter model constructor.
     * @property {module:model/Parameter}
     */
    Parameter,

    /**
     * The Process model constructor.
     * @property {module:model/Process}
     */
    Process,

    /**
     * The TimeInterval model constructor.
     * @property {module:model/TimeInterval}
     */
    TimeInterval,

    /**
     * The Unit model constructor.
     * @property {module:model/Unit}
     */
    Unit,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The VariablePresentation model constructor.
     * @property {module:model/VariablePresentation}
     */
    VariablePresentation,

    /**
    * The DatasetspecificationApi service constructor.
    * @property {module:api/DatasetspecificationApi}
    */
    DatasetspecificationApi,

    /**
    * The ModelApi service constructor.
    * @property {module:api/ModelApi}
    */
    ModelApi,

    /**
    * The ModelconfigurationApi service constructor.
    * @property {module:api/ModelconfigurationApi}
    */
    ModelconfigurationApi,

    /**
    * The ModelversionApi service constructor.
    * @property {module:api/ModelversionApi}
    */
    ModelversionApi,

    /**
    * The ParameterApi service constructor.
    * @property {module:api/ParameterApi}
    */
    ParameterApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
